### ISSUE TITLE
Same author but with different names

### ISSUE THREAD

**Issue by jyriand** [jsomers/git-game#19]
I have a repository where some authors show up multiple times. For example "John Doe" and "john.doe".  This names should match, currently don't.

**Comment by jsomers** [comment]
@jyriand Yeah that's a good call, we should de-dupe the names. Will see if I can get some time to cook up a solution...

**Comment by ehmorris** [comment]
![screen shot 2015-05-05 at 4 02 15 pm](https://cloud.githubusercontent.com/assets/654275/7481750/6ad91870-f340-11e4-9bb6-b1ba3c832199.png)

**Comment by bieron** [comment]
I don't think this is a bug. Addressing this issue would make the game hardly playable in repos, where two or more distinct persons are named similarly.

**Comment by makiftutuncu** [comment]
I think this happens because committer email addresses are different. I appear twice in my repository because my git config and GitHub emails are different (the commits I make on my own are from one and commits GitHub makes in my name when I merge PRs are from other email account with name being the same). So the solution is to de-dupe by committer emails and show emails next to committer names in the selection.

**Comment by NxSoftware** [comment]
> 

Could some kind of configuration be implemented such that it's up to the user to register a list of names that should be considered the same person?
